---
hcloudcli_version: v1.43.1
hcloudcli_tmp_dir: /tmp/hcloud
hcloudcli_install_dir: /usr/local/bin
hcloudcli_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
hcloudcli_release_filename: "hcloud-linux-{{ hcloudcli_arch }}"
hcloudcli_release_archive: "{{ hcloudcli_release_filename }}.tar.gz"
hcloudcli_repo_url: "https://github.com/hetznercloud/cli/releases/download"
hcloudcli_release_url: "{{ hcloudcli_repo_url }}/{{ hcloudcli_version }}/{{ hcloudcli_release_archive }}"
