---
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

docker_packages_state: present

# Service options.
docker_service_manage: true
docker_service_state: started
docker_service_enabled: true

# Docker repo.
docker_add_repo: true
docker_repo_url: "https://download.docker.com/linux/debian"
docker_apt_release_channel: stable
docker_apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
docker_apt_gpg_dest: "/etc/apt/keyrings/docker.asc"
docker_apt_repo_url: "{{ docker_repo_url }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_repo_entry: "deb [arch={{ docker_apt_arch }} signed-by={{ docker_apt_gpg_dest }}] {{ docker_apt_repo_url }}"
docker_apt_ignore_key_error: true
docker_apt_gpg_key_url: "{{ docker_repo_url }}/gpg"
docker_apt_filename: "docker"

# Docker daemon options.
docker_daemon_options: {}

# Docker daemon environment variables.
docker_daemon_environment: {}
