---
# defaults file for jeppech.podman

# Service options.
podman_service_manage: true
podman_service_state: started
podman_service_enabled: true

# Podman binary.
podman_version: v5.0.2
podman_tmp_dir: /tmp/podman
podman_install_dir: /usr/local/bin
podman_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
podman_release_filename: "podman-remote-static-linux_{{ podman_arch }}"
podman_release_archive: "{{ podman_release_filename }}.tar.gz"
podman_repo_url: "https://github.com/containers/podman/releases/download"
podman_release_url: "{{ podman_repo_url }}/{{ podman_version }}/{{ podman_release_archive }}"

# Install state.
podman_state_key: "{{ role_name }}_{{ podman_version }}"
