---
- name: Assert install state.
  ansible.builtin.include_role:
    name: jeppech.install_state
    vars:
      install_state: {
        key: "{{ podman_state_key }}",
        name: "{{ role_name }}",
        state: "{{ podman_version }}"
      }

- name: Install Podman.
  ansible.builtin.include_tasks:
    file: install.yml
  when: lookup('vars', podman_state_key) | bool

- name: Commit new state.
  ansible.builtin.include_role:
    name: jeppech.install_state
    vars:
      install_state: {
        name: "{{ role_name }}",
        state: "{{ podman_version }}",
        commit: true
      }
  when: lookup('vars', podman_state_key) | bool
