---
- name: Create temporary directory for CNI plugins.
  ansible.builtin.file:
    path: "{{ cni_plugins_tmp_dir }}/{{ cni_plugins_release_filename }}"
    state: directory
    mode: "0755"


- name: Download CNI plugins from GitHub.
  ansible.builtin.get_url:
    url: "{{ cni_plugins_release_url }}"
    dest: "{{ cni_plugins_tmp_dir }}"
    mode: "0755"

- name: Extract CNI plugins from archive.
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ cni_plugins_tmp_dir }}/{{ cni_plugins_release_archive }}"
    dest: "{{ cni_plugins_tmp_dir }}/{{ cni_plugins_release_filename }}"
    mode: "0755"
    exclude:
      - LICENSE
      - README.md

- name: Ensure CNI install directory.
  ansible.builtin.file:
    path: "{{ cni_plugins_install_dir }}"
    owner: "{{ cni_plugins_owner }}"
    group: "{{ cni_plugins_group }}"
    mode: "0755"
    state: directory

- name: Copy CNI plugins to install directory.
  ansible.builtin.copy:
    remote_src: true
    src: "{{ cni_plugins_tmp_dir }}/{{ cni_plugins_release_filename }}/"
    dest: "{{ cni_plugins_install_dir }}/"
    owner: "{{ cni_plugins_owner }}"
    group: "{{ cni_plugins_group }}"
    mode: "0755"
