---
cni_plugins_owner: root
cni_plugins_group: root
cni_plugins_version: v1.4.1
cni_plugins_install_dir: /opt/cni/bin
cni_plugins_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
cni_plugins_github_repo: https://api.github.com/repos/containernetworking/plugins
cni_plugins_release_url: "{{ cni_plugins_github_repo }}/releases/tags/{{ cni_plugins_version }}"
cni_plugins_tarball: "cni-plugins-linux-{{ cni_plugins_arch }}-{{ cni_plugins_version }}.tgz"
