---
cni_plugins_owner: root
cni_plugins_group: root
cni_plugins_version: v1.4.1
cni_plugins_tmp_dir: /tmp/cni_plugins
cni_plugins_install_dir: /opt/cni/bin
cni_plugins_arch: "{{ 'arm' if ansible_architecture == 'aarch64' else 'amd64' }}"
cni_plugins_release_filename: "cni-plugins-linux-{{ cni_plugins_arch }}-{{ cni_plugins_version }}"
cni_plugins_release_archive: "{{ cni_plugins_release_filename }}.tgz"
cni_plugins_repo_url: "https://github.com/containernetworking/plugins/releases/download"
cni_plugins_release_url: "{{ cni_plugins_repo_url }}/{{ cni_plugins_version }}/{{ cni_plugins_release_archive }}"
