---
- name: Create temporary directory for hcloud.
  ansible.builtin.file:
    path: "{{ hcloudcli_tmp_dir }}"
    state: directory
    mode: "0755"

- name: Download hcloud-cli from GitHub.
  ansible.builtin.get_url:
    url: "{{ hcloudcli_release_url }}"
    dest: "{{ hcloudcli_tmp_dir }}"
    mode: "0755"

- name: Extract hcloud-cli from archive.
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ hcloudcli_tmp_dir }}/{{ hcloudcli_release_archive }}"
    dest: "{{ hcloudcli_tmp_dir }}"
    mode: "0755"

- name: Copy hcloud binary to install directory.
  ansible.builtin.copy:
    remote_src: true
    src: "{{ hcloudcli_tmp_dir }}/hcloud"
    dest: "{{ hcloudcli_install_dir }}/hcloud"
    owner: "root"
    group: "root"
    mode: "0755"
