---
# defaults file for jeppech.podman

# Podman binary.
crun_version: 1.14.4
crun_tmp_dir: /tmp/crun
crun_install_dir: /usr/bin
crun_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
crun_release_filename: "crun-{{ crun_version }}-linux-{{ crun_arch }}"
crun_plugins_repo_url: "https://github.com/containers/crun/releases/download"
crun_release_url: "{{ crun_plugins_repo_url }}/{{ crun_version }}/{{ crun_release_filename }}"
