---
- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - ca-certificates
    state: present
  when: docker_add_repo | bool

- name: Add Docker key.
  ansible.builtin.get_url:
    url: "{{ docker_apt_gpg_key_url }}"
    dest: "{{ docker_apt_gpg_dest }}"
    mode: "0644"
    force: false
  register: add_repository_key
  ignore_errors: "{{ docker_apt_ignore_key_error }}"
  when: docker_add_repo | bool

- name: Add Docker repository.
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repo_entry }}"
    state: present
    filename: "{{ docker_apt_filename }}"
    update_cache: true
  when: docker_add_repo | bool
